/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminBanksRouteImport } from './routes/admin.banks'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminLoanTypesRouteImport } from './routes/admin.loan-types'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminStatusWorkflowRouteImport } from './routes/admin.status-workflow'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWebsiteRouteImport } from './routes/admin.website'
import { Route as BankerTokenRouteImport } from './routes/banker.$token'
import { Route as CustomerApplicationsRouteImport } from './routes/customer.applications'
import { Route as CustomerDashboardRouteImport } from './routes/customer.dashboard'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as LoansSlugRouteImport } from './routes/loans.$slug'
import { Route as TeamApplicationsRouteImport } from './routes/team.applications'
import { Route as TeamCommissionsRouteImport } from './routes/team.commissions'
import { Route as TeamDashboardRouteImport } from './routes/team.dashboard'
import { Route as TeamLeadsRouteImport } from './routes/team.leads'
import { Route as TeamReportsRouteImport } from './routes/team.reports'
import { Route as TeamShareLinksRouteImport } from './routes/team.share-links'
import { Route as AdminApplicationsIdRouteImport } from './routes/admin.applications.$id'
import { Route as CustomerApplicationsIdRouteImport } from './routes/customer.applications.$id'
import { Route as TeamApplicationsIdRouteImport } from './routes/team.applications.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBanksRoute = AdminBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoanTypesRoute = AdminLoanTypesRouteImport.update({
  id: '/loan-types',
  path: '/loan-types',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatusWorkflowRoute = AdminStatusWorkflowRouteImport.update({
  id: '/status-workflow',
  path: '/status-workflow',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminRoute,
} as any)
const BankerTokenRoute = BankerTokenRouteImport.update({
  id: '/banker/$token',
  path: '/banker/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerApplicationsRoute = CustomerApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const LoansSlugRoute = LoansSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LoansRoute,
} as any)
const TeamApplicationsRoute = TeamApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => TeamRoute,
} as any)
const TeamCommissionsRoute = TeamCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => TeamRoute,
} as any)
const TeamDashboardRoute = TeamDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeamRoute,
} as any)
const TeamLeadsRoute = TeamLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => TeamRoute,
} as any)
const TeamReportsRoute = TeamReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeamRoute,
} as any)
const TeamShareLinksRoute = TeamShareLinksRouteImport.update({
  id: '/share-links',
  path: '/share-links',
  getParentRoute: () => TeamRoute,
} as any)
const AdminApplicationsIdRoute = AdminApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminApplicationsRoute,
} as any)
const CustomerApplicationsIdRoute = CustomerApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomerApplicationsRoute,
} as any)
const TeamApplicationsIdRoute = TeamApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeamApplicationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/customer': typeof CustomerRouteWithChildren
  '/loans': typeof LoansRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/team': typeof TeamRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/banks': typeof AdminBanksRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/loan-types': typeof AdminLoanTypesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/status-workflow': typeof AdminStatusWorkflowRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/banker/$token': typeof BankerTokenRoute
  '/customer/applications': typeof CustomerApplicationsRouteWithChildren
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/loans/$slug': typeof LoansSlugRoute
  '/team/applications': typeof TeamApplicationsRouteWithChildren
  '/team/commissions': typeof TeamCommissionsRoute
  '/team/dashboard': typeof TeamDashboardRoute
  '/team/leads': typeof TeamLeadsRoute
  '/team/reports': typeof TeamReportsRoute
  '/team/share-links': typeof TeamShareLinksRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/customer/applications/$id': typeof CustomerApplicationsIdRoute
  '/team/applications/$id': typeof TeamApplicationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/customer': typeof CustomerRouteWithChildren
  '/loans': typeof LoansRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/team': typeof TeamRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/banks': typeof AdminBanksRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/loan-types': typeof AdminLoanTypesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/status-workflow': typeof AdminStatusWorkflowRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/banker/$token': typeof BankerTokenRoute
  '/customer/applications': typeof CustomerApplicationsRouteWithChildren
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/loans/$slug': typeof LoansSlugRoute
  '/team/applications': typeof TeamApplicationsRouteWithChildren
  '/team/commissions': typeof TeamCommissionsRoute
  '/team/dashboard': typeof TeamDashboardRoute
  '/team/leads': typeof TeamLeadsRoute
  '/team/reports': typeof TeamReportsRoute
  '/team/share-links': typeof TeamShareLinksRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/customer/applications/$id': typeof CustomerApplicationsIdRoute
  '/team/applications/$id': typeof TeamApplicationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/customer': typeof CustomerRouteWithChildren
  '/loans': typeof LoansRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/team': typeof TeamRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/banks': typeof AdminBanksRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/loan-types': typeof AdminLoanTypesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/status-workflow': typeof AdminStatusWorkflowRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/banker/$token': typeof BankerTokenRoute
  '/customer/applications': typeof CustomerApplicationsRouteWithChildren
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/loans/$slug': typeof LoansSlugRoute
  '/team/applications': typeof TeamApplicationsRouteWithChildren
  '/team/commissions': typeof TeamCommissionsRoute
  '/team/dashboard': typeof TeamDashboardRoute
  '/team/leads': typeof TeamLeadsRoute
  '/team/reports': typeof TeamReportsRoute
  '/team/share-links': typeof TeamShareLinksRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/customer/applications/$id': typeof CustomerApplicationsIdRoute
  '/team/applications/$id': typeof TeamApplicationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/contact'
    | '/customer'
    | '/loans'
    | '/login'
    | '/register'
    | '/team'
    | '/admin/applications'
    | '/admin/banks'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/loan-types'
    | '/admin/reports'
    | '/admin/status-workflow'
    | '/admin/users'
    | '/admin/website'
    | '/banker/$token'
    | '/customer/applications'
    | '/customer/dashboard'
    | '/customer/profile'
    | '/loans/$slug'
    | '/team/applications'
    | '/team/commissions'
    | '/team/dashboard'
    | '/team/leads'
    | '/team/reports'
    | '/team/share-links'
    | '/admin/applications/$id'
    | '/customer/applications/$id'
    | '/team/applications/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/contact'
    | '/customer'
    | '/loans'
    | '/login'
    | '/register'
    | '/team'
    | '/admin/applications'
    | '/admin/banks'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/loan-types'
    | '/admin/reports'
    | '/admin/status-workflow'
    | '/admin/users'
    | '/admin/website'
    | '/banker/$token'
    | '/customer/applications'
    | '/customer/dashboard'
    | '/customer/profile'
    | '/loans/$slug'
    | '/team/applications'
    | '/team/commissions'
    | '/team/dashboard'
    | '/team/leads'
    | '/team/reports'
    | '/team/share-links'
    | '/admin/applications/$id'
    | '/customer/applications/$id'
    | '/team/applications/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/contact'
    | '/customer'
    | '/loans'
    | '/login'
    | '/register'
    | '/team'
    | '/admin/applications'
    | '/admin/banks'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/loan-types'
    | '/admin/reports'
    | '/admin/status-workflow'
    | '/admin/users'
    | '/admin/website'
    | '/banker/$token'
    | '/customer/applications'
    | '/customer/dashboard'
    | '/customer/profile'
    | '/loans/$slug'
    | '/team/applications'
    | '/team/commissions'
    | '/team/dashboard'
    | '/team/leads'
    | '/team/reports'
    | '/team/share-links'
    | '/admin/applications/$id'
    | '/customer/applications/$id'
    | '/team/applications/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  LoansRoute: typeof LoansRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TeamRoute: typeof TeamRouteWithChildren
  BankerTokenRoute: typeof BankerTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banks': {
      id: '/admin/banks'
      path: '/banks'
      fullPath: '/admin/banks'
      preLoaderRoute: typeof AdminBanksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loan-types': {
      id: '/admin/loan-types'
      path: '/loan-types'
      fullPath: '/admin/loan-types'
      preLoaderRoute: typeof AdminLoanTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/status-workflow': {
      id: '/admin/status-workflow'
      path: '/status-workflow'
      fullPath: '/admin/status-workflow'
      preLoaderRoute: typeof AdminStatusWorkflowRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/banker/$token': {
      id: '/banker/$token'
      path: '/banker/$token'
      fullPath: '/banker/$token'
      preLoaderRoute: typeof BankerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/applications': {
      id: '/customer/applications'
      path: '/applications'
      fullPath: '/customer/applications'
      preLoaderRoute: typeof CustomerApplicationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/loans/$slug': {
      id: '/loans/$slug'
      path: '/$slug'
      fullPath: '/loans/$slug'
      preLoaderRoute: typeof LoansSlugRouteImport
      parentRoute: typeof LoansRoute
    }
    '/team/applications': {
      id: '/team/applications'
      path: '/applications'
      fullPath: '/team/applications'
      preLoaderRoute: typeof TeamApplicationsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/commissions': {
      id: '/team/commissions'
      path: '/commissions'
      fullPath: '/team/commissions'
      preLoaderRoute: typeof TeamCommissionsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/dashboard': {
      id: '/team/dashboard'
      path: '/dashboard'
      fullPath: '/team/dashboard'
      preLoaderRoute: typeof TeamDashboardRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/leads': {
      id: '/team/leads'
      path: '/leads'
      fullPath: '/team/leads'
      preLoaderRoute: typeof TeamLeadsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/reports': {
      id: '/team/reports'
      path: '/reports'
      fullPath: '/team/reports'
      preLoaderRoute: typeof TeamReportsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/share-links': {
      id: '/team/share-links'
      path: '/share-links'
      fullPath: '/team/share-links'
      preLoaderRoute: typeof TeamShareLinksRouteImport
      parentRoute: typeof TeamRoute
    }
    '/admin/applications/$id': {
      id: '/admin/applications/$id'
      path: '/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AdminApplicationsIdRouteImport
      parentRoute: typeof AdminApplicationsRoute
    }
    '/customer/applications/$id': {
      id: '/customer/applications/$id'
      path: '/$id'
      fullPath: '/customer/applications/$id'
      preLoaderRoute: typeof CustomerApplicationsIdRouteImport
      parentRoute: typeof CustomerApplicationsRoute
    }
    '/team/applications/$id': {
      id: '/team/applications/$id'
      path: '/$id'
      fullPath: '/team/applications/$id'
      preLoaderRoute: typeof TeamApplicationsIdRouteImport
      parentRoute: typeof TeamApplicationsRoute
    }
  }
}

interface AdminApplicationsRouteChildren {
  AdminApplicationsIdRoute: typeof AdminApplicationsIdRoute
}

const AdminApplicationsRouteChildren: AdminApplicationsRouteChildren = {
  AdminApplicationsIdRoute: AdminApplicationsIdRoute,
}

const AdminApplicationsRouteWithChildren =
  AdminApplicationsRoute._addFileChildren(AdminApplicationsRouteChildren)

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRouteWithChildren
  AdminBanksRoute: typeof AdminBanksRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoanTypesRoute: typeof AdminLoanTypesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStatusWorkflowRoute: typeof AdminStatusWorkflowRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebsiteRoute: typeof AdminWebsiteRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRouteWithChildren,
  AdminBanksRoute: AdminBanksRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoanTypesRoute: AdminLoanTypesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStatusWorkflowRoute: AdminStatusWorkflowRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebsiteRoute: AdminWebsiteRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerApplicationsRouteChildren {
  CustomerApplicationsIdRoute: typeof CustomerApplicationsIdRoute
}

const CustomerApplicationsRouteChildren: CustomerApplicationsRouteChildren = {
  CustomerApplicationsIdRoute: CustomerApplicationsIdRoute,
}

const CustomerApplicationsRouteWithChildren =
  CustomerApplicationsRoute._addFileChildren(CustomerApplicationsRouteChildren)

interface CustomerRouteChildren {
  CustomerApplicationsRoute: typeof CustomerApplicationsRouteWithChildren
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerApplicationsRoute: CustomerApplicationsRouteWithChildren,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerProfileRoute: CustomerProfileRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface LoansRouteChildren {
  LoansSlugRoute: typeof LoansSlugRoute
}

const LoansRouteChildren: LoansRouteChildren = {
  LoansSlugRoute: LoansSlugRoute,
}

const LoansRouteWithChildren = LoansRoute._addFileChildren(LoansRouteChildren)

interface TeamApplicationsRouteChildren {
  TeamApplicationsIdRoute: typeof TeamApplicationsIdRoute
}

const TeamApplicationsRouteChildren: TeamApplicationsRouteChildren = {
  TeamApplicationsIdRoute: TeamApplicationsIdRoute,
}

const TeamApplicationsRouteWithChildren =
  TeamApplicationsRoute._addFileChildren(TeamApplicationsRouteChildren)

interface TeamRouteChildren {
  TeamApplicationsRoute: typeof TeamApplicationsRouteWithChildren
  TeamCommissionsRoute: typeof TeamCommissionsRoute
  TeamDashboardRoute: typeof TeamDashboardRoute
  TeamLeadsRoute: typeof TeamLeadsRoute
  TeamReportsRoute: typeof TeamReportsRoute
  TeamShareLinksRoute: typeof TeamShareLinksRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamApplicationsRoute: TeamApplicationsRouteWithChildren,
  TeamCommissionsRoute: TeamCommissionsRoute,
  TeamDashboardRoute: TeamDashboardRoute,
  TeamLeadsRoute: TeamLeadsRoute,
  TeamReportsRoute: TeamReportsRoute,
  TeamShareLinksRoute: TeamShareLinksRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  CustomerRoute: CustomerRouteWithChildren,
  LoansRoute: LoansRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TeamRoute: TeamRouteWithChildren,
  BankerTokenRoute: BankerTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
